# Generated by Django 3.1.2 on 2021-02-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210218_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cont_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('msg', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
